[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --tb=short
filterwarnings =
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning:jose.jwt
    ignore:'crypt' is deprecated:DeprecationWarning:passlib.utils
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
