"""add grievances, institute documents, camera feeds, renewal status

Revision ID: 4b1fdea9cbae
Revises: 6d3660c1da79
Create Date: 2026-09-20 15:26:38.519027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types  # custom GUID column type used by every table


# revision identifiers, used by Alembic.
revision: str = '4b1fdea9cbae'
down_revision: Union[str, None] = '6d3660c1da79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_feeds',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('institute_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grievances',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('institute_id', app.db.types.GUID(), nullable=False),
    sa.Column('submitted_by_id', app.db.types.GUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institute_documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('institute_id', app.db.types.GUID(), nullable=False),
    sa.Column('alert_id', app.db.types.GUID(), nullable=True),
    sa.Column('uploaded_by_id', app.db.types.GUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('institutes', sa.Column('renewal_status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutes', 'renewal_status')
    op.drop_table('institute_documents')
    op.drop_table('grievances')
    op.drop_table('camera_feeds')
    # ### end Alembic commands ###
